### ISSUE TITLE
Can't install?

### ISSUE THREAD

**Issue by maathieu** [auxesis/cucumber-nagios#20]
Using Ruby 1.9.1, latest stable build on windows XP. When I run "gem install cucumber-nagios", I get the following text:

<pre>
Building native extensions.  This could take a while...
ERROR:  Error installing cucumber-nagios:
        ERROR: Failed to build gem native extension.

C:/Ruby191/bin/ruby.exe extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary libraries and/or headers.  Check the mkmf.log file for more details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby191/bin/ruby
C:/Ruby191/lib/ruby/1.9.1/mkmf.rb:364:in `try_do': The complier failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/Ruby191/lib/ruby/1.9.1/mkmf.rb:427:in `try_compile'
        from C:/Ruby191/lib/ruby/1.9.1/mkmf.rb:545:in `try_var'
        from C:/Ruby191/lib/ruby/1.9.1/mkmf.rb:793:in `block in have_var'
        from C:/Ruby191/lib/ruby/1.9.1/mkmf.rb:670:in `block in checking_for'
        from C:/Ruby191/lib/ruby/1.9.1/mkmf.rb:276:in `block (2 levels) in postpone'
        from C:/Ruby191/lib/ruby/1.9.1/mkmf.rb:250:in `open'
        from C:/Ruby191/lib/ruby/1.9.1/mkmf.rb:276:in `block in postpone'
        from C:/Ruby191/lib/ruby/1.9.1/mkmf.rb:250:in `open'
        from C:/Ruby191/lib/ruby/1.9.1/mkmf.rb:272:in `postpone'
        from C:/Ruby191/lib/ruby/1.9.1/mkmf.rb:669:in `checking_for'
        from C:/Ruby191/lib/ruby/1.9.1/mkmf.rb:792:in `have_var'
        from extconf.rb:16:in `<main>'

Gem files will remain installed in C:/Ruby191/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10 for inspection.
Results logged to C:/Ruby191/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/ext/gem_make.out
</pre>

Am I missing something here? It's a fresh Ruby install with cucumber added using gem install.

**Comment by maathieu** [comment]
OK, answering my own question :-).

On a fresh ruby install on windows, you need to download and install the Ruby Installer AND the development kit, otherwise "gem install" will fail. They are both located in RubyForge in the same project (Ruby Installer for Windows).

Hope this helps more newbs...

mat'
