### ISSUE TITLE
Abend: cucumber-nagios-gen project --pretend private.org

### ISSUE THREAD

**Issue by hedgehog** [auxesis/cucumber-nagios#48]
```
$ cucumber-nagios-gen project --pretend private.org
Generating with project generator (just pretending):
     [ADDED]  .gitignore
     [ADDED]  .bzrignore
     [ADDED]  Gemfile
     [ADDED]  features/steps
     [ADDED]  features/support
     [ADDED]  README
/home/hedge/.rvm/gems/ruby-1.9.2-p136@bbb-bdd-sys/gems/cucumber-nagios-0.8.10/bin/cucumber-nagios-gen:54:in `chdir': No such file or directory - /usr/src/bigbluebutton/labs/bdd/system/private.org (Errno::ENOENT)
    from /home/hedge/.rvm/gems/ruby-1.9.2-p136@bbb-bdd-sys/gems/cucumber-nagios-0.8.10/bin/cucumber-nagios-gen:54:in `git_init'
    from /home/hedge/.rvm/gems/ruby-1.9.2-p136@bbb-bdd-sys/gems/cucumber-nagios-0.8.10/bin/cucumber-nagios-gen:48:in `after_run'
    from /home/hedge/.rvm/gems/ruby-1.9.2-p136@bbb-bdd-sys/gems/templater-1.0.0/lib/templater/cli/generator.rb:78:in `run'
    from /home/hedge/.rvm/gems/ruby-1.9.2-p136@bbb-bdd-sys/gems/templater-1.0.0/lib/templater/cli/manifold.rb:24:in `run'
    from /home/hedge/.rvm/gems/ruby-1.9.2-p136@bbb-bdd-sys/gems/templater-1.0.0/lib/templater/manifold.rb:80:in `run_cli'
    from /home/hedge/.rvm/gems/ruby-1.9.2-p136@bbb-bdd-sys/gems/cucumber-nagios-0.8.10/bin/cucumber-nagios-gen:127:in `<top (required)>'
    from /home/hedge/.rvm/gems/ruby-1.9.2-p136@bbb-bdd-sys/bin/cucumber-nagios-gen:19:in `load'
    from /home/hedge/.rvm/gems/ruby-1.9.2-p136@bbb-bdd-sys/bin/cucumber-nagios-gen:19:in `<main>'
```

**Comment by auxesis** [comment]
Thanks for the patch! 

Your fix is in 0.9.0.
