### ISSUE TITLE
cucumber-nagios does not find definitions

### ISSUE THREAD

**Issue by Finkregh** [auxesis/cucumber-nagios#79]
this might be connected to #77 , my installation does not find anything at all (absolute/relative paths do not matter).

``` bash
> uname -a
Linux jim4 2.6.32-5-amd64 #1 SMP Fri Sep 9 20:23:16 UTC 2011 x86_64 GNU/Linux

> cat /etc/debian_version
6.0.2

> set |grep GEM
GEM_HOME=/home/ol/devel/ruby_gems
GEM_PATH=/home/ol/devel/ruby_gems/gems

 > gem -v
1.3.7

> bundle install
Using eventmachine (0.12.10) 
Using amqp (0.6.7) 
Using builder (3.0.0) 
Using bundler (1.0.21) 
Using diff-lcs (1.1.3) 
Using json (1.6.1) 
Using gherkin (2.5.4) 
Using term-ansicolor (1.0.7) 
Using cucumber (1.1.0) 
Using nokogiri (1.5.0) 
Using mechanize (1.0.0) 
Using net-ssh (2.1.4) 
Using rspec-core (2.7.1) 
Using rspec-expectations (2.7.0) 
Using rspec-mocks (2.7.0) 
Using rspec (2.7.0) 
Using extlib (0.9.15) 
Using highline (1.6.2) 
Using templater (1.0.0) 
Using rack (1.3.5) 
Using rack-test (0.6.1) 
Using webrat (0.7.2) 
Using cucumber-nagios (0.9.2) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.

> bundle show cucumber-nagios
/home/ol/devel/ruby_gems/gems/cucumber-nagios-0.9.2

> echo $PATH | grep ruby_gems
/home/ol/devel/ruby_gems/bin:[...]
```

``` bash
> cucumber --format pretty --require features/ features/www.google.com/content.feature 
Feature: www.google.com
  It should be up

  Scenario: Visiting home page           # features/www.google.com/content.feature:4
    When I go to "http://www.google.com" # features/www.google.com/content.feature:5
      Ambiguous match of "I go to "http://www.google.com"":

      features/steps/http_steps.rb:11:in `/^I go to "(.*)"$/'
      cucumber-nagios-0.9.2/lib/cucumber/nagios/steps/http_steps.rb:11:in `/^I go to "(.*)"$/'

      You can run again with --guess to make Cucumber be more smart about it
       (Cucumber::Ambiguous)
      features/www.google.com/content.feature:5:in `When I go to "http://www.google.com"'
    Then the request should succeed      # features/www.google.com/content.feature:6
      Ambiguous match of "the request should succeed":

      features/steps/http_steps.rb:64:in `/^the (.*) ?request should succeed/'
      cucumber-nagios-0.9.2/lib/cucumber/nagios/steps/http_steps.rb:64:in `/^the (.*) ?request should succeed/'

      You can run again with --guess to make Cucumber be more smart about it
       (Cucumber::Ambiguous)
      features/www.google.com/content.feature:6:in `Then the request should succeed'

Failing Scenarios:
cucumber features/www.google.com/content.feature:4 # Scenario: Visiting home page

1 scenario (1 failed)
2 steps (2 failed)
0m0.005s
```

``` bash
> cucumber-nagios features/www.google.com/content.feature --prettyFeature: www.google.com
  It should be up

  Scenario: Visiting home page           # features/www.google.com/content.feature:4
    When I go to "http://www.google.com" # features/www.google.com/content.feature:5
      Ambiguous match of "I go to "http://www.google.com"":

      features/steps/http_steps.rb:11:in `/^I go to "(.*)"$/'
      cucumber-nagios-0.9.2/lib/cucumber/nagios/steps/http_steps.rb:11:in `/^I go to "(.*)"$/'

      You can run again with --guess to make Cucumber be more smart about it
       (Cucumber::Ambiguous)
      features/www.google.com/content.feature:5:in `When I go to "http://www.google.com"'
    Then the request should succeed      # features/www.google.com/content.feature:6
      Ambiguous match of "the request should succeed":

      features/steps/http_steps.rb:64:in `/^the (.*) ?request should succeed/'
      cucumber-nagios-0.9.2/lib/cucumber/nagios/steps/http_steps.rb:64:in `/^the (.*) ?request should succeed/'

      You can run again with --guess to make Cucumber be more smart about it
       (Cucumber::Ambiguous)
      features/www.google.com/content.feature:6:in `Then the request should succeed'

Failing Scenarios:
cucumber features/www.google.com/content.feature:4 # Scenario: Visiting home page

1 scenario (1 failed)
2 steps (2 failed)
0m0.004s
```

**Comment by Finkregh** [comment]
i forgot:

``` bash
> cucumber-nagios-gen feature www.google.com content
Generating with feature generator:
 [IDENTICAL]  features/www.google.com/content.feature
 [IDENTICAL]  features/www.google.com/steps/content_steps.rb
```
